package com.example.spending.data

import androidx.room.Entity
import androidx.room.PrimaryKey

// The User data class represents a user in the database
@Entity(tableName = "user") // Specifies that this class will be mapped to a table named "user"
data class User(
    // The id field is the primary key for this entity and will be auto-generated by Room when a new User is inserted into the database.
    @PrimaryKey(autoGenerate = true) val id: Int = 0,

    // The username field stores the user's username.
    // It’s typically used for login or user identification purposes.
    val username: String,

    // The password field stores the user's password.
    // It should be stored securely, typically in a hashed form for security purposes.
    val password: String
)
